# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx

language: R
sudo: false
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran rpack"

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
